#!/usr/bin/env python3
"""
Report generator for CDR/IPDR Analyzer.
Produces HTML reports with embedded tables and charts.
"""

import os
import json
from datetime import datetime
from pathlib import Path

import pandas as pd
from app.analyzer import IPDRAnalyzer, _human_bytes


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: #f8f9fa; font-family: 'Segoe UI', sans-serif; }
        .report-header { background: linear-gradient(135deg, #1a237e, #283593);
            color: white; padding: 40px 0; margin-bottom: 30px; }
        .stat-card { border: none; border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1); transition: transform 0.2s; }
        .stat-card:hover { transform: translateY(-3px); }
        .stat-card h3 { color: #1a237e; font-weight: bold; }
        .section { background: white; border-radius: 12px; padding: 24px;
            margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        h2 { color: #1a237e; border-bottom: 3px solid #1a237e;
            padding-bottom: 8px; margin-bottom: 20px; }
        h4 { color: #283593; margin-top: 20px; }
        .table th { font-size: 0.85rem; }
        .table td { font-size: 0.85rem; }
        .flag { color: #dc3545; font-weight: bold; }
    </style>
</head>
<body>
    <div class="report-header text-center">
        <h1 class="display-5 fw-bold">{{ record_type }} Analysis Report</h1>
        <p class="lead">Generated: {{ generated_at }}</p>
        <p>Total Records: <strong>{{ total_records }}</strong> |
           Date Range: <strong>{{ date_range }}</strong></p>
    </div>
    <div class="container">
        {{ content }}
        <footer class="text-center text-muted py-4">
            <small>Generated by CDR/IPDR Examination & Analysis Tool</small>
        </footer>
    </div>
</body>
</html>"""


class ReportGenerator:
    """Generate comprehensive HTML reports."""

    def __init__(self, analyzer, output_dir='./output'):
        self.analyzer = analyzer
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _render_table(self, data, headers=None):
        if not data:
            return '<p class="text-muted">No data available.</p>'
        if headers is None:
            headers = list(data[0].keys())
        rows = ''.join('<tr>' + ''.join(f'<td>{row.get(h, "")}</td>' for h in headers) + '</tr>' for row in data)
        hdr = ''.join(f'<th>{h}</th>' for h in headers)
        return f'<div class="table-responsive"><table class="table table-striped table-hover table-sm"><thead class="table-dark"><tr>{hdr}</tr></thead><tbody>{rows}</tbody></table></div>'

    def generate_html_report(self, viz_files=None):
        stats = self.analyzer.summary()
        hourly = self.analyzer.hourly_activity()
        weekday = self.analyzer.weekday_activity()
        top = self.analyzer.top_talkers(20)
        content = []

        # Duration section
        if 'duration' in stats:
            d = stats['duration']
            content.append(f'''
            <div class="section"><h2>Duration Statistics</h2>
            <div class="row">
                <div class="col-md-3 col-6 mb-3"><div class="card stat-card"><div class="card-body text-center"><h5>Min</h5><h3>{d["min"]:.1f}s</h3></div></div></div>
                <div class="col-md-3 col-6 mb-3"><div class="card stat-card"><div class="card-body text-center"><h5>Max</h5><h3>{d["max"]:.1f}s</h3></div></div></div>
                <div class="col-md-3 col-6 mb-3"><div class="card stat-card"><div class="card-body text-center"><h5>Mean</h5><h3>{d["mean"]:.1f}s</h3></div></div></div>
                <div class="col-md-3 col-6 mb-3"><div class="card stat-card"><div class="card-body text-center"><h5>Total</h5><h3>{d["total"]:.0f}s</h3></div></div></div>
            </div></div>''')

        # Activity patterns
        pat_html = ''
        if not hourly.empty:
            peak = hourly.loc[hourly['count'].idxmax()]
            pat_html += f'<h4>Hourly Activity</h4><p>Peak hour: <strong>{int(peak["hour"])}:00</strong> ({int(peak["count"])} records)</p>{self._render_table(hourly.to_dict("records"), ["hour", "count"])}'
        if not weekday.empty:
            peak = weekday.loc[weekday['count'].idxmax()]
            pat_html += f'<h4>Weekly Activity</h4><p>Busiest day: <strong>{peak["weekday"]}</strong> ({int(peak["count"])} records)</p>{self._render_table(weekday.to_dict("records"), ["weekday", "count"])}'
        if pat_html:
            content.append(f'<div class="section"><h2>Activity Patterns</h2>{pat_html}</div>')

        # Top entities
        top_html = ''
        for role, label in [('caller', 'Callers'), ('callee', 'Destinations')]:
            if role in top:
                top_html += f'<h4>Top {label}</h4>{self._render_table(top[role].to_dict("records"))}'
        if top_html:
            content.append(f'<div class="section"><h2>Top Entities</h2>{top_html}</div>')

        # IPDR specific
        if isinstance(self.analyzer, IPDRAnalyzer):
            ipdr_s = ''
            proto = self.analyzer.protocol_distribution()
            if proto:
                rows = ''.join(f'<tr><td>{k}</td><td>{v}</td></tr>' for k, v in list(proto.items())[:15])
                ipdr_s += f'<h4>Protocol Distribution</h4><table class="table table-sm table-striped"><thead><tr><th>Protocol</th><th>Count</th></tr></thead><tbody>{rows}</tbody></table>'
            bw = self.analyzer.bandwidth_analysis()
            if bw:
                ipdr_s += f'<h4>Bandwidth Summary</h4><p>Total Data Volume: <strong>{_human_bytes(bw.get("total_bytes", 0))}</strong></p>'
            if ipdr_s:
                content.append(f'<div class="section"><h2>Protocol & Bandwidth</h2>{ipdr_s}</div>')

        # Visualizations
        if viz_files:
            imgs = ''
            for f in viz_files:
                if f.endswith('.png'):
                    rel = os.path.relpath(f, str(self.output_dir))
                    imgs += f'<div class="col-md-6 mb-4"><div class="card"><img src="{rel}" class="card-img-top"></div></div>'
            if imgs:
                content.append(f'<div class="section"><h2>Visualizations</h2><div class="row">{imgs}</div></div>')

        # Anomalies
        anom = self.analyzer.detect_anomalies()
        if not anom.empty:
            cols = [c for c in anom.columns[:8] if c != 'z_score']
            content.append(f'<div class="section"><h2>Detected Anomalies <span class="flag">({len(anom)} found)</span></h2>{self._render_table(anom.head(50).to_dict("records"), cols)}</div>')

        # Render
        dr = stats.get('date_range', {})
        html = HTML_TEMPLATE.replace('{{ title }}', f"{stats['record_type']} Analysis Report")
        html = html.replace('{{ record_type }}', stats['record_type'])
        html = html.replace('{{ generated_at }}', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        html = html.replace('{{ total_records }}', f"{stats['total_records']:,}")
        html = html.replace('{{ date_range }}', f"{dr.get('start', 'N/A')[:10]} → {dr.get('end', 'N/A')[:10]}")
        html = html.replace('{{ content }}', ''.join(content))

        path = self.output_dir / 'analysis_report.html'
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)

        # Also export CSV
        csv_path = self.output_dir / 'analysis_data.csv'
        self.analyzer.df.to_csv(csv_path, index=False)

        return str(path)
